server:
  port: 8084
  
gateway:
    url: http://gateway:8080

patient:
  url: http://patient-service:8081
  url-local: http://localhost:8081
history:
  url: http://history-service:8083
  url-local: http://localhost:8083